// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Rx92rg0N6v9KwdD2uPG1mCKnOyWcJ8M',
    appId: '1:423541042778:web:6e942872e30bbd8854b263',
    messagingSenderId: '423541042778',
    projectId: 'buy-stuff-39f69',
    authDomain: 'buy-stuff-39f69.firebaseapp.com',
    storageBucket: 'buy-stuff-39f69.firebasestorage.app',
    measurementId: 'G-7X24M1Y2PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4agsBGH7FvLhSr_IGM7g4B3nEs2snFoI',
    appId: '1:423541042778:android:c4fa8525cbd4b30354b263',
    messagingSenderId: '423541042778',
    projectId: 'buy-stuff-39f69',
    storageBucket: 'buy-stuff-39f69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfGbtZlE_hWrdo9Wftwio5hyqiCBPmiSY',
    appId: '1:423541042778:ios:4c80cbff0d6ac7b754b263',
    messagingSenderId: '423541042778',
    projectId: 'buy-stuff-39f69',
    storageBucket: 'buy-stuff-39f69.firebasestorage.app',
    iosClientId: '423541042778-7uuopncpj35f24jcdaod84m6qksd884k.apps.googleusercontent.com',
    iosBundleId: 'com.thepocketmerlin.ecommerceDummyApp',
  );

}